
development:
  adapter: mysql2
  database: eyc_development
  username: root
  password:
  encoding: utf8

test:
  adapter: mysql2
  database: eyc_test
  username: root
  password:
  encoding: utf8

production:
  adapter: mysql2
  database: eyc_production
  username: root
  password: 
  encoding: utf8

